### ISSUE TITLE
Failed to enable plugin: mojoconsole-plus

### ISSUE THREAD

**Issue by keqingyyds** [gc-mojoconsole/gc-mojoconsole-backend#14]
Failed to enable plugin: mojoconsole-plus

**Comment by keqingyyds** [comment]
19:19:24 <ERROR:PluginManager> Failed to enable plugin: mojoconsole-plus
java.lang.NoClassDefFoundError: emu/grasscutter/Configuration
        at com.mojo.consoleplus.ConsolePlus.onEnable(ConsolePlus.java:45)
        at emu.grasscutter.plugin.PluginManager.lambda$enablePlugins$2(PluginManager.java:201)
        at java.base/java.util.LinkedHashMap.forEach(LinkedHashMap.java:721)
        at emu.grasscutter.plugin.PluginManager.enablePlugins(PluginManager.java:198)
        at emu.grasscutter.Grasscutter.main(Grasscutter.java:206)
Caused by: java.lang.ClassNotFoundException: emu.grasscutter.Configuration
        at java.base/java.net.URLClassLoader.findClass(URLClassLoader.java:445)
        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:587)
        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:520)
        ... 5 common frames omitted

**Comment by mingjun97** [comment]
Fixed in the latest release. Thanks for reporting! 

https://github.com/gc-mojoconsole/gc-mojoconsole-backend/releases/tag/dev-1.4.0

**Comment by mingjun97** [comment]
You may reopen this issue if your problem consist with the latest release. Thank you!
如果更新到最新的mojoconsole版本还是报错的话，你可以重新打开此issue。
